# Generated by Django 6.1.1 on 2026-09-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=100)),
                ('qtpagina', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
